logging:
  level:
    ROOT: INFO
    com.jbr.sandwich: DEBUG

spring:
  datasource:
    url: ${db.pdn.sandwich.server}?autoReconnect=true&useSSL=false
    username: ${db.pdn.sandwich.user}
    password: ${db.pdn.sandwich.password}
